SSLProxyEngine On
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
ProxyPass /__/auth https://agora-mujeres.firebaseapp.com/__/auth
ProxyPassReverse /__/auth https://agora-mujeres.firebaseapp.com/__/auth
ProxyPass /api http://127.0.0.1:8001/api
ProxyPassReverse /api http://127.0.0.1:8001/api
Header always set Cross-Origin-Opener-Policy "unsafe-none"
